# HG changeset patch
# User Rik <rik@octave.org>
# Date 1426197632 25200
#      Thu Mar 12 15:00:32 2015 -0700
# Node ID 2d5cbb6ac845dcb71b71602d4627131446a2ed8c
# Parent  f0e5c6742716bbeff8188165c4963d12642b72b8
fail.m: Use internal variable name in BIST test (bug #44525).

* fail.m: Rename variable 'a' to '__a__' in case there is an a.m m-file.

diff --git a/scripts/testfun/fail.m b/scripts/testfun/fail.m
--- a/scripts/testfun/fail.m
+++ b/scripts/testfun/fail.m
@@ -141,16 +141,16 @@ endfunction
 %!fail ("fail ('[1,2]*[2;3]', 'nonconformant')", "expected error <nonconformant> but got none")
 %!fail ("fail ('[1,2]*[2,3]', 'usage:')", "expected error <usage:>\nbut got.*nonconformant")
 %!fail ("warning ('test warning')", "warning", "test warning");
 
 #%!fail ("warning ('next test')",'warning','next test');  # only allowed one warning test?!?
 
 ## Test that fail() itself will generate an error
 %!error <expected error> fail ("1")
-%!error <'a' undefined> fail ("a*[2;3]", "nonconformant")
-%!error <expected error .usage:>  fail ("a*[2,3]", "usage:")
+%!error <'__a__' undefined> fail ("__a__*[2;3]", "nonconformant")
+%!error <expected error .usage:>  fail ("__a__*[2,3]", "usage:")
 %!error <warning failure> fail ("warning ('warning failure')", "warning", "success")
 
 ## Test input validation
 %!error fail ()
 %!error fail (1,2,3,4)
 
