# HG changeset patch
# User jwe
# Date 1059426486 0
#      Mon Jul 28 21:08:06 2003 +0000
# Node ID 6a1e6e87f143950f3c2486724159838ed17c98b2
# Parent  e606bf485c1c87d5258799929742e06357a10883
[project @ 2003-07-28 21:08:06 by jwe]

diff --git a/test/octave.test/eval-catch/eval-catch.exp b/test/octave.test/eval-catch/eval-catch.exp
--- a/test/octave.test/eval-catch/eval-catch.exp
+++ b/test/octave.test/eval-catch/eval-catch.exp
@@ -36,15 +36,17 @@ do_test eval-catch-7.m
 ## handle nested eval: eval in try-string
 set test eval-catch-8
 set prog_output "__error_text__ = `a' undefined.*\n\n__error_text__ = `b' undefined.*\n$"
 do_test eval-catch-8.m
 
 ## handle nested eval: eval nested in catch-string
 set test eval-catch-9
 set prog_output "__error_text__ = `a' undefined.*\n\n__error_text__ = `b' undefined.*\n$"
+setup_xfail *-*-*
 do_test eval-catch-9.m
 
 ## re-throw an error
 set test eval-catch-10
 set prog_output "__error_text__ = rethrow: `a' undefined.*\n"
+setup_xfail *-*-*
 do_test eval-catch-10.m
 
diff --git a/test/octave.test/try/try.exp b/test/octave.test/try/try.exp
--- a/test/octave.test/try/try.exp
+++ b/test/octave.test/try/try.exp
@@ -36,14 +36,16 @@ do_test try-7.m
 ## handle nested try-catch-block: try nested in try
 set test try-8
 set prog_output "__error_text__ = `a' undefined.*\n\n__error_text__ = `b' undefined.*\n$"
 do_test try-8.m
 
 ## handle nested try-catch-block: try nested in catch
 set test try-9
 set prog_output "__error_text__ = `a' undefined.*\n\n__error_text__ = `b' undefined.*\n$"
+setup_xfail *-*-*
 do_test try-9.m
 
 ## re-throw an error
 set test try-10
 set prog_output "__error_text__ = rethrow: `a' undefined.*\n"
+setup_xfail *-*-*
 do_test try-10.m
